# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='price',
            new_name='rate',
        ),
    ]
