# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
