# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation_app', '0002_auto_20180517_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Gym',
            new_name='Membership',
        ),
    ]
