# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation_app', '0003_auto_20180517_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipManager',
        ),
    ]
