# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation_app', '0003_remove_membership_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='description',
        ),
    ]
